apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      name: student-app
      labels:
        app: student-app
    spec:
      containers:
      - name: student-app
        image: chetanpatel/studentapp:latest
        ports:
          - containerPort: 8080
            name: studentapp-port 
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_host
