apiVersion: v1
kind: Service
metadata:
  name: student-app-service
spec:
  type: LoadBalancer
  selector:
    app: student-app 
  ports:
  - protocol: TCP
    port: 8080
    targetPort: studentapp-port
