version: "3"
services:
  studentapp:
    build: .
    container_name: studentapp
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/student_db
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_USER=postgres
         - POSTGRES_DB=student_db
    restart: always

volumes:
  postgres-data:
